type GymName = string;
type GymOptionDataType = GymName[];
export const GYM_OPTION: GymOptionDataType = [
  "Boulder Planet (Sembawang)",
  "Boulder Planet (Taiseng)",
  "Boruda",
  "Fit Bloc (Kentridge)",
  "Fit Bloc (Depot Height)",
  "Lighthouse",
  "BFF (Bukit Timah)",
  "BFF (Bendemeer)",
];

export const GYM_MAPPING = {
  "boulder_planet_(sembawang)": "Boulder Planet (Sembawang)",
  "boulder_planet_(taiseng)": "Boulder Planet (Taiseng)",
  boruda: "Boruda",
  "fit_bloc_(kentridge)": "Fit Bloc (Kentridge)",
  "fit_bloc_(depot_height)": "Fit Bloc (Depot Height)",
  lighthouse: "Lighthouse",
  "bff_(bukit_timah)": "BFF (Bukit Timah)",
  "bff_(bendemeer)": "BFF (Bendemeer)",
};

type GradeType = string;
type GradeDataType = Record<string, GradeType[]>;
export const GRADE_OPTION: GradeDataType = {
  "boulder_planet_(sembawang)": [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "W",
  ],
  "boulder_planet_(taiseng)": [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "W",
  ],
  boruda: [
    "10Q",
    "9Q",
    "8Q",
    "7Q",
    "6Q",
    "5Q",
    "4Q",
    "3Q",
    "2Q",
    "1Q",
    "1D",
    "2D",
    "W",
  ],
  "fit_bloc_(kentridge)": ["0", "1", "2", "3", "4", "5", "6", "7", "8", "W"],
  "fit_bloc_(depot_height)": ["0", "1", "2", "3", "4", "5", "6", "7", "8", "W"],
  lighthouse: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
  "bff_(bukit_timah)": [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
  ],
  "bff_(bendemeer)": [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
  ],
};

type ColorType = string;
type ColorDataType = ColorType[];
export const COLOR_OPTION: ColorDataType = [
  "Red",
  "Green",
  "Blue",
  "Cyan",
  "Turquoise",
  "Purple",
  "White",
  "Black",
];
